# Generated by Django 3.2.20 on 2023-07-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230724_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profl_pic',
            field=models.ImageField(blank=True, default='/img/user.png', null=True, upload_to='img'),
        ),
    ]
